# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Environment setup
      run: |
        source ~/venv3.11/bin/activate
        bash scripts/osx-setup.sh        
    - name: Generate localization
      run: |
        bash scripts/osx-translations.sh
        python3 scripts/compile_lang.py
        python3 scripts/dump_crowdin_progress.py
    - name: Build application
        python3 db_update.py
        export PYFA_VERSION="$(python3 scripts/dump_version.py)"
        bash scripts/osx-package.sh
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist-app
        path: dist/*.zip
        
